# Generated by Django 2.2 on 2019-09-09 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("speciesinfo", "0001_initial")]

    operations = [
        migrations.AlterModelTable(name="ability", table="ability"),
        migrations.AlterModelTable(name="biome", table="biome"),
        migrations.AlterModelTable(name="bodyplan", table="body_plan"),
        migrations.AlterModelTable(name="egggroup", table="egg_group"),
        migrations.AlterModelTable(name="pokecategory", table="zc_pkmn_cat"),
        migrations.AlterModelTable(name="pokemon", table="pokémon"),
    ]
