# Generated by Django 2.2.5 on 2019-10-31 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("speciesinfo", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="bodyplan",
            name="alt_name",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="bodyplan",
            name="description",
            field=models.CharField(blank=True, max_length=69, null=True),
        ),
        migrations.AlterField(
            model_name="bodyplan",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="bodyplan",
            name="notes",
            field=models.CharField(blank=True, max_length=69, null=True),
        ),
    ]
