# Generated by Django 2.2.5 on 2019-10-30 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("nestlist", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="nstrawrpt",
            name="nsla_pk",
            field=models.ForeignKey(
                db_column="nsla_pk",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="report_audit",
                to="nestlist.NstSpeciesListArchive",
            ),
        )
    ]
