# Generated by Django 2.2 on 2019-01-29 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("nestlist", "0002_auto_20190126_0411")]

    operations = [
        migrations.DeleteModel(name="Ability"),
        migrations.DeleteModel(name="Biome"),
        migrations.DeleteModel(name="BodyPlan"),
        migrations.DeleteModel(name="EggGroup"),
        migrations.DeleteModel(name="Generation"),
        migrations.DeleteModel(name="GoIvFloor"),
        migrations.DeleteModel(name="GoPowerupLevel"),
        migrations.DeleteModel(name="GoRaidHp"),
        migrations.DeleteModel(name="GoTrainerLevel"),
        migrations.DeleteModel(name="GoWeather"),
        migrations.DeleteModel(name="PogoTeam"),
        migrations.DeleteModel(name="PokeCategory"),
        migrations.DeleteModel(name="Pokemon"),
        migrations.DeleteModel(name="Type"),
        migrations.DeleteModel(name="TypeEffectiveness"),
        migrations.DeleteModel(name="TypeEffectivenessRating"),
    ]
