# Generated by Django 2.2.5 on 2019-10-31 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nestlist", "0002_auto_20191030_0356"),
    ]

    operations = [
        migrations.RemoveField(model_name="nstadminemail", name="e_mail"),
        migrations.AddField(
            model_name="nstadminemail",
            name="auth_user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nest_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="nstadminemail",
            name="is_bot",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "human"), (2, "system"), (1, "survey"), (3, "scanner")],
                default=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="nstneighborhood",
            name="region",
            field=models.ManyToManyField(
                blank=True,
                related_name="neighborhoods",
                to="nestlist.NstCombinedRegion",
            ),
        ),
    ]
