# Generated by Django 2.2.5 on 2019-11-14 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("nestlist", "0003_auto_20191031_0403")]

    operations = [
        migrations.AlterField(
            model_name="nstadminemail",
            name="auth_user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nest_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="nstadminemail",
            name="name",
            field=models.CharField(default="n/a", max_length=90),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="nstlocation",
            name="duplicate_of",
            field=models.ForeignKey(
                blank=True,
                db_column="duplicate_of",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prior_entries",
                to="nestlist.NstLocation",
            ),
        ),
        migrations.AlterField(
            model_name="nstlocation",
            name="park_system",
            field=models.ForeignKey(
                blank=True,
                db_column="park_system",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="nestlist.NstParkSystem",
            ),
        ),
    ]
