# Generated by Django 2.2.5 on 2020-01-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("nestlist", "0004_auto_20191114_0559")]

    operations = [
        migrations.AddField(
            model_name="nstmetropolismajor",
            name="alternate_report_url",
            field=models.URLField(blank=True, null=True),
        )
    ]
