# Generated by Django 2.2 on 2019-10-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("nestlist", "0005_auto_20190909_1451")]

    operations = [
        migrations.RemoveField(model_name="nstrawrpt", name="raw_species_txt"),
        migrations.AlterField(
            model_name="nstrawrpt",
            name="raw_species_num",
            field=models.CharField(max_length=120, null=True),
        ),
    ]
