# Generated by Django 2.2 on 2019-10-10 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("nestlist", "0006_auto_20191007_2155")]

    operations = [
        migrations.DeleteModel(name="NestSpecies"),
        migrations.RemoveField(model_name="nstrawrpt", name="dedupe_sig"),
        migrations.AlterField(
            model_name="nstrawrpt",
            name="attempted_dex_num",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="speciesinfo.Pokemon",
            ),
        ),
    ]
